#pragma once

#include "libavz.h"

#define PEASHOOTER APEASHOOTER
#define SUNFLOWER ASUNFLOWER
#define CHERRY_BOMB ACHERRY_BOMB
#define WALL_NUT AWALL_NUT
#define POTATO_MINE APOTATO_MINE
#define SNOW_PEA ASNOW_PEA
#define CHOMPER ACHOMPER
#define REPEATER AREPEATER
#define PUFF_SHROOM APUFF_SHROOM
#define SUN_SHROOM ASUN_SHROOM
#define FUME_SHROOM AFUME_SHROOM
#define GRAVE_BUSTER AGRAVE_BUSTER
#define HYPNO_SHROOM AHYPNO_SHROOM
#define SCAREDY_SHROOM ASCAREDY_SHROOM
#define ICE_SHROOM AICE_SHROOM
#define DOOM_SHROOM ADOOM_SHROOM
#define LILY_PAD ALILY_PAD
#define SQUASH ASQUASH
#define THREEPEATER ATHREEPEATER
#define TANGLE_KELP ATANGLE_KELP
#define JALAPENO AJALAPENO
#define SPIKEWEED ASPIKEWEED
#define TORCHWOOD ATORCHWOOD
#define TALL_NUT ATALL_NUT
#define SEA_SHROOM ASEA_SHROOM
#define PLANTERN APLANTERN
#define CACTUS ACACTUS
#define BLOVER ABLOVER
#define SPLIT_PEA ASPLIT_PEA
#define STARFRUIT ASTARFRUIT
#define PUMPKIN APUMPKIN
#define MAGNET_SHROOM AMAGNET_SHROOM
#define CABBAGE_PULT ACABBAGE_PULT
#define FLOWER_POT AFLOWER_POT
#define KERNEL_PULT AKERNEL_PULT
#define COFFEE_BEAN ACOFFEE_BEAN
#define GARLIC AGARLIC
#define UMBRELLA_LEAF AUMBRELLA_LEAF
#define MARIGOLD AMARIGOLD
#define MELON_PULT AMELON_PULT
#define GATLING_PEA AGATLING_PEA
#define TWIN_SUNFLOWER ATWIN_SUNFLOWER
#define GLOOM_SHROOM AGLOOM_SHROOM
#define CATTAIL ACATTAIL
#define WINTER_MELON AWINTER_MELON
#define GOLD_MAGNET AGOLD_MAGNET
#define SPIKEROCK ASPIKEROCK
#define COB_CANNON ACOB_CANNON
#define IMITATER AIMITATOR
#define M_PEASHOOTER AM_PEASHOOTER
#define M_SUNFLOWER AM_SUNFLOWER
#define M_CHERRY_BOMB AM_CHERRY_BOMB
#define M_WALL_NUT AM_WALL_NUT
#define M_POTATO_MINE AM_POTATO_MINE
#define M_SNOW_PEA AM_SNOW_PEA
#define M_CHOMPER AM_CHOMPER
#define M_REPEATER AM_REPEATER
#define M_PUFF_SHROOM AM_PUFF_SHROOM
#define M_SUN_SHROOM AM_SUN_SHROOM
#define M_FUME_SHROOM AM_FUME_SHROOM
#define M_GRAVE_BUSTER AM_GRAVE_BUSTER
#define M_HYPNO_SHROOM AM_HYPNO_SHROOM
#define M_SCAREDY_SHROOM AM_SCAREDY_SHROOM
#define M_ICE_SHROOM AM_ICE_SHROOM
#define M_DOOM_SHROOM AM_DOOM_SHROOM
#define M_LILY_PAD AM_LILY_PAD
#define M_SQUASH AM_SQUASH
#define M_THREEPEATER AM_THREEPEATER
#define M_TANGLE_KELP AM_TANGLE_KELP
#define M_JALAPENO AM_JALAPENO
#define M_SPIKEWEED AM_SPIKEWEED
#define M_TORCHWOOD AM_TORCHWOOD
#define M_TALL_NUT AM_TALL_NUT
#define M_SEA_SHROOM AM_SEA_SHROOM
#define M_PLANTERN AM_PLANTERN
#define M_CACTUS AM_CACTUS
#define M_BLOVER AM_BLOVER
#define M_SPLIT_PEA AM_SPLIT_PEA
#define M_STARFRUIT AM_STARFRUIT
#define M_PUMPKIN AM_PUMPKIN
#define M_MAGNET_SHROOM AM_MAGNET_SHROOM
#define M_CABBAGE_PULT AM_CABBAGE_PULT
#define M_FLOWER_POT AM_FLOWER_POT
#define M_KERNEL_PULT AM_KERNEL_PULT
#define M_COFFEE_BEAN AM_COFFEE_BEAN
#define M_GARLIC AM_GARLIC
#define M_UMBRELLA_LEAF AM_UMBRELLA_LEAF
#define M_MARIGOLD AM_MARIGOLD
#define M_MELON_PULT AM_MELON_PULT

#define ZOMBIE AZOMBIE
#define FLAG_ZOMBIE AFLAG_ZOMBIE
#define CONEHEAD_ZOMBIE ACONEHEAD_ZOMBIE
#define POLE_VAULTING_ZOMBIE APOLE_VAULTING_ZOMBIE
#define BUCKETHEAD_ZOMBIE ABUCKETHEAD_ZOMBIE
#define NEWSPAPER_ZOMBIE ANEWSPAPER_ZOMBIE
#define SCREEN_DOOR_ZOMBIE ASCREEN_DOOR_ZOMBIE
#define FOOTBALL_ZOMBIE AFOOTBALL_ZOMBIE
#define DANCING_ZOMBIE ADANCING_ZOMBIE
#define BACKUP_DANCER ABACKUP_DANCER
#define DUCKY_TUBE_ZOMBIE ADUCKY_TUBE_ZOMBIE
#define SNORKEL_ZOMBIE ASNORKEL_ZOMBIE
#define ZOMBONI AZOMBONI
#define ZOMBIE_BOBSLED_TEAM AZOMBIE_BOBSLED_TEAM
#define DOLPHIN_RIDER_ZOMBIE ADOLPHIN_RIDER_ZOMBIE
#define JACK_IN_THE_BOX_ZOMBIE AJACK_IN_THE_BOX_ZOMBIE
#define BALLOON_ZOMBIE ABALLOON_ZOMBIE
#define DIGGER_ZOMBIE ADIGGER_ZOMBIE
#define POGO_ZOMBIE APOGO_ZOMBIE
#define ZOMBIE_YETI AZOMBIE_YETI
#define BUNGEE_ZOMBIE ABUNGEE_ZOMBIE
#define LADDER_ZOMBIE ALADDER_ZOMBIE
#define CATAPULT_ZOMBIE ACATAPULT_ZOMBIE
#define GARGANTUAR AGARGANTUAR
#define IMP AIMP
#define DR_ZOMBOSS ADR_ZOMBOSS
#define PEASHOOTER_ZOMBIE APEASHOOTER_ZOMBIE
#define WALL_NUT_ZOMBIE AWALL_NUT_ZOMBIE
#define JALAPENO_ZOMBIE AJALAPENO_ZOMBIE
#define GATLING_PEA_ZOMBIE AGATLING_PEA_ZOMBIE
#define SQUASH_ZOMBIE ASQUASH_ZOMBIE
#define TALL_NUT_ZOMBIE ATALL_NUT_ZOMBIE
#define GIGA_GARGANTUAR AGIGA_GARGANTUAR

#define AliveFilter AAliveFilter
#define alivePlaceItemFilter aAlivePlaceItemFilter
#define alivePlantFilter aAlivePlantFilter
#define aliveZombieFilter aAliveZombieFilter
#define BackToMain ABackToMain
#define cobManager aCobManager
#define CobManager ACobManager
#define CoLaunch ACoLaunch
#define Connect AConnect
#define Console AConsole
#define Coroutine ACoroutine
#define EnterGame AEnterGame
#define GetCardIndex AGetCardIndex
#define GetInternalLogger AGetInternalLogger
#define GetMainObject AGetMainObject
#define GetPlantIndex AGetPlantIndex
#define GetPlantIndices AGetPlantIndices
#define GetPlantPtr AGetPlantPtr
#define GetPlantPtrs AGetPlantPtrs
#define GetPvzBase AGetPvzBase
#define GetZombieTypeList AGetZombieTypeList
#define Grid AGrid
#define iceFiller aIceFiller
#define IsSeedUsable AIsSeedUsable
#define IsZombieExist AIsZombieExist
#define Logger ALogger
#define LogLevel ALogLevel
#define MaidCheats AMaidCheats
#define NowDelayTime ANowDelayTime
#define NowTime ANowTime
#define NowWave ANowWave
#define OnAfterInject AOnAfterInject
#define OnAfterScript AOnAfterScript
#define OnAfterTick AOnAfterTick
#define OnBeforeExit AOnBeforeExit
#define OnBeforeScript AOnBeforeScript
#define OnBeforeTick AOnBeforeTick
#define OnEnterFight AOnEnterFight
#define OnExitFight AOnExitFight
#define painter aPainter
#define Plant APlant
#define plantFixer aPlantFixer
#define PlantFixer APlantFixer
#define PlantType APlantType
#define Position APosition
#define PvzStruct APvzStruct
#define RangeIn ARangeIn
#define ReloadMode AReloadMode
#define RemovePlant ARemovePlant
#define SaveAllRegister ASaveAllRegister
#define Script AScript
#define SetAdvancedPause ASetAdvancedPause
#define SetGameSpeed ASetGameSpeed
#define SetInternalLogger ASetInternalLogger
#define SetReloadMode ASetReloadMode
#define SetWavelength ASetWavelength
#define SetZombieMode ASetZombieMode
#define SetZombies ASetZombies
#define SkipTick ASkipTick
#define StrToWstr AStrToWstr
#define Text AText
#define TickRunner ATickRunner
#define Time ATime
#define Timeline ATimeline
#define Zombie AZombie
#define ZombieType AZombieType

// SimpleAvZ Macros
#define CHERRY CHERRY_BOMB
#define POTATO POTATO_MINE
#define PUFF PUFF_SHROOM
#define SUN SUN_SHROOM
#define SCAREDY SCAREDY_SHROOM
#define ICE ICE_SHROOM
#define DOOM DOOM_SHROOM
#define LILY LILY_PAD
#define JALA JALAPENO
#define SPIKE SPIKEWEED
#define POT FLOWER_POT
#define KERNEL KERNEL_PULT
#define COFFEE COFFEE_BEAN
#define LEAF UMBRELLA_LEAF
#define COB COB_CANNON

#define M_CHERRY M_CHERRY_BOMB
#define M_PUFF M_PUFF_SHROOM
#define M_ICE M_ICE_SHROOM
#define M_DOOM M_DOOM_SHROOM
#define M_JALA M_JALAPENO

#define GARG GARGANTUAR
#define GIGA GIGA_GARGANTUAR