name: CI

on: [push]

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-commit-message
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '(.+\/.+): release (.+)'

      - name: Generate release
        if: ${{ steps.match-commit-message.outputs.match != '' }}
        run: bash generate-release.sh ${{ github.event.head_commit.message }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ steps.match-commit-message.outputs.match != '' }}
        with:
          commit_message: '${{ steps.match-commit-message.outputs.group1 }}: generate ${{ steps.match-commit-message.outputs.group2 }} release files'

  sync-to-gitlab:
    runs-on: ubuntu-latest
    needs: generate-release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: 'https://gitlab.com/avzlib/AvZLib'
          target-username: AlumKal
          target-token: ${{ secrets.GITLAB_PASSWORD }}
